# Generated by Django 5.1.1 on 2025-04-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibleByAdmin', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('clap', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(max_length=1000)),
                ('author_note', models.TextField(blank=True, max_length=2000, null=True)),
                ('pairing', models.CharField(max_length=200, null=True)),
                ('pairing_type', models.CharField(choices=[('gen', 'Pas de couple'), ('F/F', 'Yuri'), ('M/M', 'Yaoi'), ('F/M', 'Hétéro'), ('poly', 'Polyamour'), ('autre', 'Autre')], default='M/M', max_length=10)),
                ('rating', models.CharField(choices=[('g', 'G'), ('t', 'T'), ('e', 'E')], default='g', max_length=6)),
                ('text_length', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('roman', 'Roman')], default='nouvelle', max_length=20)),
                ('complete', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archives.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.fic')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author_note', models.TextField(blank=True, max_length=2000, null=True)),
                ('content', models.TextField(max_length=1000000)),
                ('fic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.fic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fic', 'number'), name='unique_chapter_number_for_fic')],
            },
        ),
    ]
