# Generated by Django 4.1.5 on 2023-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fic',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
