# Generated by Django 4.1.5 on 2023-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_chapter_author_note_alter_author_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='author_note',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
