# Generated by Django 4.1.5 on 2023-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_alter_chapter_author_note_alter_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='author_note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
