# Generated by Django 4.1.5 on 2023-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_alter_chapter_author_note_alter_chapter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='fic',
            name='author_note',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
