# Generated by Django 4.1.5 on 2023-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fic',
            name='text_length',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('roman', 'Roman')], default='nouvelle', max_length=20),
        ),
        migrations.AlterField(
            model_name='fic',
            name='author_note',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fic',
            name='rating',
            field=models.CharField(choices=[('g', 'G'), ('t', 'T'), ('e', 'E')], default='g', max_length=6),
        ),
    ]
